### ISSUE TITLE
WP3 Exercise 5: Keyboard scanning v 2.0

### ISSUE THREAD

**Issue by litvem** [litvem/DIT633-V23-Group-11#25]

**Comment by Quinstedt** [comment]
[Related issues](https://github.com/litvem/DIT633-V23-Group-11/commit/f25653553ffb0b59209eb81637619b99621e31f9) https://github.com/litvem/DIT633-V23-Group-11/issues/24 [and # 25](https://github.com/litvem/DIT633-V23-Group-11/commit/f25653553ffb0b59209eb81637619b99621e31f9) …
commit: [f256535](https://github.com/litvem/DIT633-V23-Group-11/commit/f25653553ffb0b59209eb81637619b99621e31f9)
Both exercise are complete and tested in tinkercad.
